# Generated by Django 3.2a1 on 2021-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_data_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
