# Generated by Django 3.2a1 on 2021-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210207_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
